question_data = [

         {"category": "Politics", "type": "multiple", "difficulty": "easy",
          "question": "Whose 2016 presidential campaign slogan was ;'Make America Great Again'?",
          "correct_answer": "Donald Trump",
          "incorrect_answers": ["Ted Cruz", "Marco Rubio", "Bernie Sanders"]},
         {"category": "Entertainment: Video Games", "type": "multiple",
          "difficulty": "medium",
          "question": "In the game Paper Mario for the Nintendo 64 the first partner you meet is a Goomba, what is its name?",
          "correct_answer": "Goombario",
          "incorrect_answers": ["Goombella", "Goombarry", "Goomby"]},
         {"category": "Entertainment: Japanese Anime & Manga", "type": "multiple",
          "difficulty": "medium",
          "question": "What year did the anime Himouto! Umaru-chan air?",
          "correct_answer": "2015", "incorrect_answers": ["2014", "2012", "2013"]},
         {"category": "Animals", "type": "multiple", "difficulty": "hard",
          "question": "Unlike on most salamanders, this part of a newt is flat?",
          "correct_answer": "Tail", "incorrect_answers": ["Head", "Teeth", "Feet"]},
         {"category": "Entertainment: Video Games", "type": "multiple",
          "difficulty": "hard",
          "question": "How many trophies are there in Super Smash Bros. for Nintendo 3DS?",
          "correct_answer": "685", "incorrect_answers": ["1360", "716", "1155"]},
         {"category": "Entertainment: Comics", "type": "multiple", "difficulty": "easy",
          "question": "What is the alter-ego of the DC comics character Superman?",
          "correct_answer": "Clark Kent",
          "incorrect_answers": ["Bruce Wayne", "Arthur Curry", "John Jones"]},
         {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
          "question": "Nephelococcygia is the practice of doing what?",
          "correct_answer": "Finding shapes in clouds",
          "incorrect_answers": ["Sleeping with your eyes open",
                                "Breaking glass with your voice",
                                "Swimming in freezing water"]},
         {"category": "Geography", "type": "multiple", "difficulty": "medium",
          "question": "How many provinces are in the Netherlands?", "correct_answer": "12",
          "incorrect_answers": ["14", "10", "13"]},
         {"category": "Entertainment: Video Games", "type": "multiple",
          "difficulty": "medium",
          "question": "Which game won the Games for Impact award in The Game Awards 2015?",
          "correct_answer": "Life is Strange",
          "incorrect_answers": ["Ori and the Blind Forest", "Rocket League",
                                "Metal Gear Solid V: The Phantom Pain"]},
         {"category": "History", "type": "multiple", "difficulty": "medium",
          "question": "John Moses Browning, the designer of the M1918 BAR (Browning Automatic Rifle) was a part of which religion?",
          "correct_answer": "Mormon",
          "incorrect_answers": ["Catholic", "Jewish", "Atheist"]}
]
